spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

logging:
  level:
    com.web.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: TRACE

cafe:
  recommendation:
    base:
      url: http://localhost:8080/dir/
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13307/cafe-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.hibernate.default_batch_fetch_size: 100
---

spring:
  config:
    activate:
      on-profile: prod
