spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13307/cafe-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

cafe:
  recommendation:
    base:
      url: http://localhost:8080/dir/

---

spring:
  config:
    activate:
      on-profile: prod
